events {}

http {
    lua_package_path "/usr/share/nginx/lua/?.lua;;";

    server {
        listen 80;

        location /lua {
            content_by_lua_file /usr/share/nginx/lua/hello.lua;
        }
    }
}