name: Docker

on:
  #schedule:
  #  - cron: '30 17 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    #container:
      #image: centos:7
      
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

#      - name: Install tools
#        run: |
#          yum install -y epel-release
#          yum install -y yum-utils createrepo

#      - name: Package
#        run: |
#          tar czf docker-offline.tar.gz docker-offline
#          # XZ_OPT='-T0 -6 -vv' tar -vvcJf docker-offline.tar.xz docker-offline

      - name: Build
        run: |
          export PROJECT_DIR=$GITHUB_WORKSPACE
          docker build \
            -f $PROJECT_DIR/docker_files/yum/old/Dockerfile \
            -t docker-offline \
            $PROJECT_DIR/docker_files/yum/old

      - name: Export
        run: |
          id=$(docker create docker-offline bash)
      
          docker cp \
            $id:/ \
            offline
      
          docker rm $id

      - name: Package
        run: |
          tar czf docker-offline.tar.gz offline

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: docker-offline
          path: docker-offline.tar.gz
          


