name: Docker

on:
  #schedule:
  #  - cron: '30 17 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    #container:
      #image: centos:7
      
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

#      - name: Install tools
#        run: |
#          yum install -y epel-release
#          yum install -y yum-utils createrepo

#      - name: Package
#        run: |
#          tar czf docker-offline.tar.gz docker-offline
#          # XZ_OPT='-T0 -6 -vv' tar -vvcJf docker-offline.tar.xz docker-offline

# cp 使用
#      - name: Build
#        run: |
#          export PROJECT_DIR=$GITHUB_WORKSPACE
#          docker build \
#            -f $PROJECT_DIR/docker_files/yum/old/Dockerfile \
#            -t docker-offline \
#            $PROJECT_DIR/docker_files/yum/old
#
#      - name: Export
#        run: |
#          id=$(docker create docker-offline bash)
#
#          docker cp \
#            $id:/ \
#            offline
#
#          docker rm $id

# 需要镜像
# docker buildx build -t offline-builder .
# docker run --rm \
#      -v $(pwd)/out:/out \
#      offline-builder \
#      cp -r /offline /out
# 不生成镜像，直接构建后就输出文件， 最后.或者指定目录，表示Dockerfile 可以访问的目录
# type=tar,dest=offline.tar  改用 tar 输出（最稳）
# --output type=local,dest=./offline  【filesystem sync 文件同步，文件多github上会卡死】
# tar -xf offline.tar -C offline --strip-components=1 offline --strip-components=1 会去掉路径里最外层的一级目录（即去掉 opt/ 这一层），结果就是 src/ 下直接是 opt 里原来的文件。

# -f $PROJECT_DIR/docker_files/yum/old/Dockerfile \ centos 7
# -f $PROJECT_DIR/docker_files/dnf/Dockerfile \ dnf新方式
# -f $PROJECT_DIR/docker_files/dnf/reposync/Dockerfile \  dnf reposync 方式
# -f $PROJECT_DIR/docker_files/yum/reposync/Dockerfile \  yum reposync 方式
# -f $PROJECT_DIR/docker_files/apt-get/debian/Dockerfile \  apt-get 方式（旧版本）
# -f $PROJECT_DIR/docker_files/apt-get/debian-new/Dockerfile \  apt 方式（新版本）
      - name: Build
        run: |
          export PROJECT_DIR=$GITHUB_WORKSPACE
          DOCKER_BUILDKIT=1 docker buildx build \
            -f $PROJECT_DIR/docker_files/apt-get/debian-new/Dockerfile \
            --output type=tar,dest=offline.tar \
            $PROJECT_DIR/docker_files/dnf
          tar -tf offline.tar
          mkdir -p offline
          tar -xf offline.tar -C offline --strip-components=1 offline

      - name: Package
        run: |
          ls -lah offline/
          tar czf docker-offline.tar.gz offline
          rm -rf offline.tar
          rm -rf offline

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: docker-offline
          path: docker-offline.tar.gz
          


